networks:
  my-net:
    external: true

volumes:
  caddy:

services:
  caddy:
    image: caddy:2.4.3-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from ${CADDY_FROM_URL} --to http://node:3000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    networks:
      - my-net

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net
    ports:
      - '3000:3000'
    tty: true